# Generated by Django 4.1 on 2022-08-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author1', models.CharField(default='', max_length=100)),
                ('author2', models.CharField(default='', max_length=100)),
                ('author3', models.CharField(default='', max_length=100)),
                ('publication_link', models.CharField(max_length=100)),
            ],
        ),
    ]
